name: kelicap_components_workspace
repository: https://github.com/dukefirehawk/kelicap_components

packages:
  - components
  # - component_gallery/gallery
  # - component_gallery/gallery_section
  # - component_gallery/examples/**

ignore:
#   - compiler
#   - web
#   - tests

command:
  bootstrap:
    usePubspecOverrides: true
