name: kelicap_components_workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

publish_to: none

workspace:
  - components
  - component_gallery/gallery
  - component_gallery/gallery_section

  
dev_dependencies:
  melos: ^8.0.0
  lints: ^6.0.0

melos:
  # All the content of your previous melos.yaml file goes here
  # (e.g., scripts, command configs, etc.)
