targets:
  $default:
    builders:
      kelicap_components|scss_builder:
        enabled: True
      kelicap_gallery|kelicap_gallery:
        enabled: False
      kelicap_gallery_section|kelicap_gallery_section:
        options:
          staticImageServer: "https://raw.githubusercontent.com"
