targets:
  $default:
    builders:
      kelicap_components|scss_builder:
        enabled: True
      kelicap|kelicap:
        generate_for:
          exclude: ["lib/**"]

builders:
  kelicap_gallery:
    target: ":kelicap_gallery"
    import: "package:kelicap_gallery/builders.dart"
    builder_factories: [
      galleryAppBuilder,
      galleryLibBuilder,
      syntaxHighlightBuilder,
    ]
    build_extensions: {
      ".html": [".dart"],
      "$web$": ["index.html", "main.dart", "style.scss"]}
    auto_apply: dependents
    runs_before: ["kelicap|kelicap", "kelicap_components|scss_builder"]
