name: kelicap_gallery
publish_to: none
environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  kelicap: ^1.0.0
  kelicap_components: ^1.0.0 
  kelicap_forms: ^1.0.0
  kelicap_router: ^1.0.0
  build: ^4.0.0
  build_config: ^1.0.0
  #mustache: ^1.0.0
  mustache_template: ^2.0.0
  lints: ^6.0.0
