name: kelicap_components
version: 1.0.0
description: Kelicap material components for Kelicap framework. 
repository: https://github.com/dukefirehawk/kelicap_components

environment:
  sdk: '>=3.12.0 <4.0.0'

resolution: workspace

dependencies:
  kelicap: ^1.0.0
  kelicap_forms: ^1.0.0
  async: ^2.1.0
  build: ^4.0.0
  build_config: ^1.0.0
  built_collection: ^5.1.1
  collection: ^1.15.0
  fixnum: ^1.0.0
  intl: ^0.20.0
  web: ^1.0.0
  logging: ^1.0.2
  meta: ^1.0.4
  observable: ^0.24.0
  protobuf: ^6.0.0
  quiver: ^3.0.1
  sass_builder: ^2.4.0+1

dev_dependencies:
  grinder: ^0.10.0
  lints: ^6.0.0
  path: ^1.6.1
  test: ^1.0.0
  build_runner: ^2.1.4
