name: material_slider_example
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'

resolution: workspace

dependencies:
  kelicap: ^1.0.0
  kelicap_components: ^1.0.0
  kelicap_gallery: ^1.0.0
  kelicap_gallery_section: ^1.0.0
  build_config: ^1.0.0

