targets:
  $default:
    builders:
      kelicap|kelicap:
        generate_for:
          exclude: [
            "lib/*.dart",
            "lib/annotation/**",
            "lib/builder/**",
            "lib/src/**",
            "lib/visitors/**",
            ]
      kelicap_components|scss_builder:
        enabled: True
    kelicap_gallery|kelicap_gallery:
        enabled: False

builders:
  kelicap_gallery_section:
    target: ':kelicap_gallery_section'
    import: 'package:kelicap_gallery_section/builder.dart'
    builder_factories: [
      'galleryInfoBuilder',
      'componentApiBuilder',
      'gallerySectionBuilder'
    ]
    build_extensions: {
      ".dart": [".gallery_info.json", ".api.dart"],
      "$lib$": ["gallery_section.dart", "gallery_section_summary.json"]}
    auto_apply: dependents
    runs_before: ["kelicap|kelicap", "kelicap_components|scss_builder"]
