name: kelicap_gallery_section
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'

resolution: workspace

dependencies:
  analyzer:  ^14.0.0
  kelicap: ^1.0.0
  kelicap_components: ^1.0.0
  kelicap_gallery: ^1.0.0
  build: ^4.0.0
  build_config: ^1.0.0
  glob: ^2.0.2
  markdown: ^7.0.2
  web: ^1.0.0
  mustache_template: ^2.0.0
  collection: ^1.18.0
  path: ^1.6.1
  sass: ^1.100.0
  sanitize_html: ^2.2.0
  lints: ^6.0.0